services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  hw1:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./StaticPages:/usr/local/apache2/htdocs

  hw2:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./Calculator:/usr/local/apache2/htdocs

  hw3:
    build:
      context: ./FormValidation
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
    - ./FormValidation:/usr/local/app

  hw4:
    build:
      context: ./Howler
      dockerfile: Dockerfile
    # image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./Howler/static:/app/static
      - ./Howler/templates:/app/templates
      - ./Howler/server.js:/app/server.js

  hw5:
    build:
      context: ./JWTAuthentication
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./JWTAuthentication:/usr/local/app
    environment:
      - PORT=80
    env_file:
      - ./Homework5/.env